-- CreateEnum
CREATE TYPE "TrainingStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "TrainingType" AS ENUM ('NR10_SEGURANCA_ELETRICIDADE_40H', 'NR10_SEP_SISTEMA_ELETRICO_POTENCIA', 'CARTA_ANUENCIA_SEP_208', 'CNH_CARTEIRA_NACIONAL_HABILITACAO', 'TREINAMENTO_DIRECAO_DEFENSIVA_208', 'CURSO_MANUSEIO_EMERGENCIAS_QUIMICAS', 'CARTA_ANUENCIA_NR12_208', 'NR12_OPERACAO_MANUTENCAO_MAQUINAS_EQUIPAMENTOS_208', 'NR35_TRABALHO_ALTURA_RESGATE_AEROGERADORES_16H', 'CARTA_ANUENCIA_NR35_208', 'NR11_TALHA_ELETRICA_208', 'COMPROVANTE_QUALIFICACAO', 'GWO_CERTIFICADO_TREINAMENTO_WINDA_208', 'GWO_BST_TRABALHO_RESGATE_ALTURA_16H_208', 'GWO_BST_PRIMEIROS_SOCORROS_208', 'GWO_BST_MANUSEIO_MANUAL_208', 'GWO_BST_COMBATE_INCENDIO_208', 'ADVANCED_RESCUE_TRAINING_ART');

-- CreateTable
CREATE TABLE "Training" (
    "id" TEXT NOT NULL,
    "type" "TrainingType" NOT NULL,
    "status" "TrainingStatus" NOT NULL DEFAULT 'PENDING',
    "fileUrl" TEXT,
    "issuedAt" DATE,
    "expiresAt" DATE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "employeeId" TEXT,

    CONSTRAINT "Training_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Training_employeeId_idx" ON "Training"("employeeId");

-- CreateIndex
CREATE INDEX "Training_status_idx" ON "Training"("status");

-- CreateIndex
CREATE INDEX "Training_expiresAt_idx" ON "Training"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "Training_employeeId_type_key" ON "Training"("employeeId", "type");

-- AddForeignKey
ALTER TABLE "Training" ADD CONSTRAINT "Training_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
